// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-1YafffkfeJGYtAHQcwuAnZYjxJMo1M',
    appId: '1:892417075594:web:51aead7bdc6c41850e0073',
    messagingSenderId: '892417075594',
    projectId: 'crud-ce1fe',
    authDomain: 'crud-ce1fe.firebaseapp.com',
    storageBucket: 'crud-ce1fe.appspot.com',
    measurementId: 'G-LW7G8F9GQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMdmT82oOWapM-Y61_3YfHO4QVP32t6Bo',
    appId: '1:892417075594:android:4c00aca480f1e53f0e0073',
    messagingSenderId: '892417075594',
    projectId: 'crud-ce1fe',
    storageBucket: 'crud-ce1fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2aigC0DXJC1dJmYX7jv_jN-fOW8vhj7E',
    appId: '1:892417075594:ios:061a67f50249c65c0e0073',
    messagingSenderId: '892417075594',
    projectId: 'crud-ce1fe',
    storageBucket: 'crud-ce1fe.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2aigC0DXJC1dJmYX7jv_jN-fOW8vhj7E',
    appId: '1:892417075594:ios:061a67f50249c65c0e0073',
    messagingSenderId: '892417075594',
    projectId: 'crud-ce1fe',
    storageBucket: 'crud-ce1fe.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW-1YafffkfeJGYtAHQcwuAnZYjxJMo1M',
    appId: '1:892417075594:web:ef1d60b2dc3b5e650e0073',
    messagingSenderId: '892417075594',
    projectId: 'crud-ce1fe',
    authDomain: 'crud-ce1fe.firebaseapp.com',
    storageBucket: 'crud-ce1fe.appspot.com',
    measurementId: 'G-4D5MK45HNZ',
  );
}
